@startuml

object " " as main
object "r: Read" as r
object "v: Validation" as v
object "p: Plateau" as p
object "j: JeuDeLaVie" as j
object "cellule: Cellule" as cellule
object "c: Coordonnee" as c

main .. r
main .. p
main .. j
r .. v
p .. cellule
cellule .. c











@enduml
